engines:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
      - TODO
  markdownlint:
    enabled: true
  duplication:
    enabled: true
ratings:
    paths:[]
exclude_path:
    tests/
