- include: centos.yml
  when: ansible_os_family == 'RedHat'
  static: no

- include: ubuntu.yml
  when: ansible_os_family == 'Debian'
  static: no

#
# General tasks for all Systems
#
- name: Snmp Copy config
  template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: 0600
  tags: snmp, service
  notify: Restart snmpd

- name: Nrpe copy config
  template:
    src: nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
  tags: nrpe, service
  notify: Restart nrpe

- name: Nrpe copy command config
  template:
    src: monitor.cfg.j2
    dest: /etc/nrpe.d/monitor.cfg
  tags: nrpe, service
  notify: Restart nrpe
